Text to speach function
Evelina-Ok/Choose-Your-Own-Adventure-language-app pull request #47
Opened 2024-12-04 15:01 UTC by Rafalzie

2024-12-04 15:35 UTC, utlandingur requested changes
make changes then ill approve

2024-12-04 15:35 UTC, utlandingur commented on src/components/BackArrow.tsx
remove empty object/curly braces

2024-12-04 15:35 UTC, utlandingur commented on src/components/options.tsx
remove unused hook and delete the hook

2024-12-04 15:35 UTC, utlandingur commented on src/components/microphone.tsx
get rid of the needless handleonclick function. just pass directly.

2024-12-04 15:35 UTC, utlandingur commented on src/hooks/useAudio.ts
delete this

2024-12-04 15:35 UTC, utlandingur commented on src/providers/storyProvider.tsx
fine but this should be in a separate branch

2024-12-04 15:52 UTC, Rafalzie commented on src/components/microphone.tsx
done

2024-12-04 15:52 UTC, Rafalzie commented on src/components/options.tsx
done i guess

2024-12-04 15:52 UTC, Rafalzie commented on src/hooks/useAudio.ts
done

2024-12-05 11:07 UTC, utlandingur approved these changes

2024-12-05 11:07 UTC, merged